stages:
  - test
  - release

dependency_scanning:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
  artifacts:
    paths: [gl-dependency-scanning-report.json]
build_docker_image:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker info
    - echo ${DOCKER_USERNAME}
    - docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
    - docker build --tag KitaitiMakoto/bibid:${CI_COMMIT_TAG} .
    - docker push KitaitiMakoto/bibid:${CI_COMMIT_TAG}
  only:
    - tags
  when: on_success
